In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [4]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [5]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
import tensorflow as tf
from tensorflow import keras 
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data = keras.datasets.fashion_mnist